- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - composer
    - simplesamlphp
    - unzip
    - git
    - php-mbstring
    - php-pdo-sqlite
  become: yes

- name: Enable apache simplesamlphp configuration
  become: yes
  command: a2enconf simplesamlphp
  args:
    creates: /etc/apache2/conf-enabled/simplesamlphp.conf
  notify:
  - restart apache2
