authirma_configuration: |
    'irma' => array(
        'authirma:IRMA',
        'irma_api_server' => 'https://irma.surfconext.nl',
        'irma_web_server' => 'https://privacybydesign.foundation/tomcat/irma_api_server',
        'jwt_privatekeyfile' => 'authirma-sk.pem',
        'jwt_apiserver_publickeyfile' => 'authirma-apiserver-pk.pem',
        'issuer_id' => 'surfnet_idp',
        'issuer_displayname' => 'SURFconext',
        'requested_attributes' => [
            [ "label" => "Institute", "attributes" => ["pbdf.pbdf.surfnet.institute"] ],
            [ "label" => "Type", "attributes" => ["pbdf.pbdf.surfnet.type"] ],
            [ "label" => "ID", "attributes" => ["pbdf.pbdf.surfnet.id"] ],
            [ "label" => "Full name", "attributes" => ["pbdf.pbdf.surfnet.fullname"] ],
            [ "label" => "Given name", "attributes" => ["pbdf.pbdf.surfnet.firstname"] ],
            [ "label" => "Family name", "attributes" => ["pbdf.pbdf.surfnet.familyname"] ],
            [ "label" => "Email address", "attributes" => ["pbdf.pbdf.surfnet.email"] ],
        ]
    ),

privatekey: "{{ lookup('file', inventory_dir+'/files/sk.pem') }}"
apiserver_publickey: "{{ lookup('file', inventory_dir+'/files/apiserver.pem') }}"

hostname: localhost
